Feature/dashboards
joseucarvajal/amplify-checkout-cart pull request #18
Opened 2022-12-13 05:51 UTC by scordero414

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/43121242/207236553-03d520d4-6a93-4aba-baac-b6181fcb915c.png">
By clicking on scordero i.e 
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/43121242/207236634-4dae2c6d-520b-4e2a-a81c-52a088a4630a.png">
By clicking on pasteur i.e
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/43121242/207236716-d8a67cbc-3698-42b3-9f0d-52abdf790aaf.png">

Logged as scordero[admin]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/43121242/207236915-b4bf0525-6146-473a-8a1e-a49d1c4a8ba0.png">
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/43121242/207236974-02c13569-6c1d-48e3-870a-fcb7a272c21b.png">

** It would be better if you set up this code and run some out of the box test

2022-12-13 12:16 UTC, Jsmorales1415 requested changes

2022-12-13 12:16 UTC, Jsmorales1415 commented on amplify-checkout-cart/src/components/dashboard/Dashboard.tsx
> +interface itemType {
Capitalize interface name

2022-12-13 12:16 UTC, Jsmorales1415 commented on amplify-checkout-cart/src/pages/dashboard/admin/index.tsx
> +      {loggedUserGroup === SUPERADMIN ? (
Wrap this with Visible component instead of doing condition manually

2022-12-13 12:16 UTC, Jsmorales1415 commented on amplify-checkout-cart/src/pages/dashboard/admin/index.tsx
> +export async function getAdminFactList({
Move this API call outside pages. Create a new folder inside src/api for this

2022-12-13 12:16 UTC, Jsmorales1415 commented on amplify-checkout-cart/src/pages/dashboard/restricted-user/index.tsx
> +      {(loggedUserGroup === ADMIN || loggedUserGroup === SUPERADMIN) ? (
Visible component

2022-12-14 00:25 UTC, Jsmorales1415 approved these changes

2022-12-14 00:26 UTC, DRodriguez322 approved these changes

2022-12-14 00:26 UTC, nicolasforeros commented on amplify-checkout-cart/src/components/common/S3Image.tsx
> +interface IS3ImageProps {
change to S3ImageProps

2022-12-14 00:27 UTC, warlesrivera approved these changes

2022-12-14 00:27 UTC, nicolasforeros commented on amplify-checkout-cart/src/components/dashboard/Dashboard.tsx
> +interface IDashboardProps {
change to DashboardProps

2022-12-14 00:27 UTC, nicolasforeros commented on amplify-checkout-cart/src/components/dashboard/DataPrompt.tsx
> +interface IDataPromptProps {
Change to DataPromptProps

2022-12-14 00:32 UTC, nicolasforeros approved these changes

2022-12-14 00:33 UTC, merged